export interface ConfiguracaoNomes {
  nome: {
    masculino: string[];
    feminino: string[];
  };
  sobrenome: {
    alta_classe?: string[];
    baixa_classe?: string[];
    sem_classe?: string[];
  };
}

const sobrenomes_elficos_alta_classe = [
  "Aerthran",
  "Amakiir",
  "Aranore",
  "Arvandor",
  "Brightblade",
  "Caerthann",
  "Dawnstar",
  "Delsaran",
  "Eversong",
  "Faelar",
  "Galanodel",
  "Glimmerwing",
  "Goldpetal",
  "Greenleaf",
  "Hysandir",
  "Ilphelkiir",
  "Imarandis",
  "Irithyll",
  "Jelenneth",
  "Leafsong",
];

const sobrenomes_elficos_baixa_classe = [
  "Ashwood",
  "Brook",
  "Clayfoot",
  "Creek",
  "Dewdrop",
  "Dust",
  "Fallow",
  "Fern",
  "Fisher",
  "Hearth",
  "Knoll",
  "Moss",
  "Oak",
  "Pebble",
  "Pine",
  "Root",
  "Shade",
  "Sprout",
  "Thorn",
  "Wild",
];

const nomes_masculinos_elficos = [
  "Adran",
  "Aelrindel",
  "Aerion",
  "Aelar",
  "Alasir",
  "Anarion",
  "Aranel",
  "Aramil",
  "Beiro",
  "Beren",
  "Cairon",
  "Caelen",
  "Celeborn",
  "Daeron",
  "Eldrin",
  "Erion",
  "Fírin",
  "Galin",
  "Glorfindel",
  "Hadarai",
  "Halamir",
  "Hareth",
  "Iaeven",
  "Iriandor",
  "Jandar",
  "Kael",
  "Laelon",
  "Thegolas",
  "Maerth",
  "Melion",
  "Mithrir",
  "Naeris",
  "Olorin",
  "Ondol",
  "Orion",
  "Peren",
  "Quarion",
  "Ranthir",
  "Riel",
  "Saeros",
  "Silvanus",
  "Tauriel",
  "Thranduil",
  "Valen",
  "Vedel",
  "Venefar",
  "Virion",
  "Voron",
  "Xandir",
  "Zevran",
];

const nomes_femininos_elficos = [
  "Adrie",
  "Aerith",
  "Aeliana",
  "Alanna",
  "Annalyn",
  "Arwen",
  "Astriel",
  "Briar",
  "Caelyn",
  "Celaena",
  "Cirilla",
  "Daenys",
  "Elara",
  "Eldana",
  "Eleniel",
  "Ellaria",
  "Enya",
  "Estel",
  "Faelan",
  "Faral",
  "Galyriel",
  "Glynnis",
  "Gwenevere",
  "Hadia",
  "Ilyana",
  "Irthiel",
  "Isyl",
  "Jessa",
  "Kaelyn",
  "Leilani",
  "Lira",
  "Lyra",
  "Maeve",
  "Mieli",
  "Niamh",
  "Nuala",
  "Ondine",
  "Oriana",
  "Perian",
  "Quelana",
  "Rina",
  "Rhiannon",
  "Saeleth",
  "Seharaphina",
  "Soriel",
  "Sylvana",
  "Thalia",
  "Verdant",
  "Zephyrine",
  "Zylara",
];

const sobrenomes_humanos_alta_classe_ocidental = [
  "Ashworth",
  "Blackwood",
  "Briarwood",
  "Fairlight",
  "Falconer",
  "Grimfang",
  "Ironhand",
  "Longstride",
  "Oakenshield",
  "Pendleton",
  "Rivers",
  "Silverstream",
  "Stonemarch",
  "Strongbow",
  "Thornwood",
  "Valerius",
  "Whitewind",
  "Willowbrook",
  "Wintergale",
  "Wyvernspur",
];
const sobrenomes_humanos_baixa_classe_ocidental = [
  "Baker",
  "Brewer",
  "Cooper",
  "Fisher",
  "Fuller",
  "Gardener",
  "Hunter",
  "Miller",
  "Shepherd",
  "Smith",
  "Taylor",
  "Thatcher",
  "Weaver",
  "Woodman",
  "Young",
  "Brooks",
  "Hill",
  "Stone",
  "Ford",
  "Dale",
];
const nomes_masculinos_humanos_ocidental = [
  "Alaric",
  "Arthur",
  "Benedict",
  "Caleb",
  "Darian",
  "Edmund",
  "Finn",
  "Gareth",
  "Henry",
  "Jasper",
  "Kaelen",
  "Liam",
  "Marcus",
  "Nolan",
  "Orin",
  "Patrick",
  "Quinn",
  "Roric",
  "Stefan",
  "Tobias",
  "Ulric",
  "Victor",
  "Wyatt",
  "Xavier",
  "Yorick",
  "Zephyr",
  "Alden",
  "Bastian",
  "Conrad",
  "Damon",
  "Elias",
  "Fletcher",
  "Garrett",
  "Heath",
  "Ignatius",
  "Julian",
  "Kieran",
  "Lysander",
  "Milo",
  "Owen",
  "Perrin",
  "Rowan",
  "Sebastian",
  "Thane",
  "Ulfric",
  "Vance",
  "Warren",
  "Zane",
  "Caspian",
  "Felix",
  "Lysander",
];
const nomes_femininos_humanos_ocidental = [
  "Adelaide",
  "Bronwyn",
  "Caitlin",
  "Daphne",
  "Elara",
  "Freya",
  "Gwendolyn",
  "Hazel",
  "Isolde",
  "Juliana",
  "Keira",
  "Lillian",
  "Maeve",
  "Nadia",
  "Oriana",
  "Penelope",
  "Rosalind",
  "Seraphina",
  "Thalia",
  "Undine",
  "Valerie",
  "Willow",
  "Xenia",
  "Yvette",
  "Zara",
  "Audrey",
  "Beatrice",
  "Clara",
  "Delia",
  "Eleanor",
  "Genevieve",
  "Helena",
  "Iris",
  "Jocelyn",
  "Katherine",
  "Lena",
  "Miriam",
  "Niamh",
  "Olive",
  "Phoebe",
  "Regan",
  "Scarlett",
  "Tessa",
  "Ursula",
  "Violet",
  "Willa",
  "Zelda",
  "Eliza",
  "Lorelei",
];

const sobrenomes_humanos_alta_classe_oriental = [
  "al-Hashem",
  "al-Kassar",
  "al-Zayid",
  "Amunhotep",
  "Ben-Hadad",
  "Dahari",
  "El-Fayoum",
  "Hathor-Ka",
  "Ib'n-Amon",
  "Khemet-Ra",
  "Majid-Awan",
  "Pharaon",
  "Rameshi",
  "Saqqara",
  "Set-Aker",
  "Thothmes",
  "Ur-Shalim",
  "Valerius",
  "Xepheris",
  "Zahi-Osir",
];
const sobrenomes_humanos_baixa_classe_oriental = [
  "Abasi",
  "Bakr",
  "Fahim",
  "Ghaleb",
  "Hadi",
  "Jaber",
  "Karim",
  "Latif",
  "Majid",
  "Nadim",
  "Qadir",
  "Rakan",
  "Sabir",
  "Samad",
  "Shafi",
  "Tariq",
  "Wali",
  "Yasin",
  "Zaki",
  "Zouhair",
];
const nomes_femininos_humanos_oriental = [
  "Aaliyah",
  "Amara",
  "Anahita",
  "Basma",
  "Dalia",
  "Elara",
  "Farah",
  "Gisela",
  "Hana",
  "Imani",
  "Jasmine",
  "Khadija",
  "Layla",
  "Maira",
  "Nadia",
  "Oriana",
  "Qara",
  "Ranya",
  "Samira",
  "Shira",
  "Soraya",
  "Tamara",
  "Zara",
  "Zahra",
  "Alia",
  "Amina",
  "Jamila",
  "Karima",
  "Laila",
  "Mona",
  "Noura",
  "Safiya",
  "Thalia",
  "Yasmin",
  "Zina",
  "Amira",
  "Dina",
  "Ghada",
  "Isra",
  "Kamila",
  "Lina",
  "Mariam",
  "Nasira",
  "Rasha",
  "Samara",
  "Shani",
  "Sultana",
  "Umaira",
  "Zahira",
  "Zulaikha",
];
const nomes_masculinos_humanos_oriental = [
  "Adem",
  "Amun-Ra",
  "Aswad",
  "Bahar",
  "Bashar",
  "Chayton",
  "Cyrus",
  "Darian",
  "Elian",
  "Farid",
  "Ghaith",
  "Hakam",
  "Imran",
  "Jarah",
  "Kaelen",
  "Khalan",
  "Maksym",
  "Nadim",
  "Omarion",
  "Qadir",
  "Rakan",
  "Ramir",
  "Sadiq",
  "Samar",
  "Tarek",
  "Usman",
  "Yahya",
  "Zafir",
  "Zane",
  "Zayd",
  "Aidan",
  "Asim",
  "Basir",
  "Dahab",
  "Fahim",
  "Jamal",
  "Kareem",
  "Malik",
  "Nasser",
  "Riyad",
  "Salim",
  "Sharif",
  "Tarik",
  "Yassir",
  "Zaman",
  "Arin",
  "Jabari",
  "Kael",
  "Rami",
  "Suleiman",
];
const sobrenomes_anoes_alta_classe = [
  "Barbadura",
  "Cascoferro",
  "Escudoforte",
  "Feitomartelo",
  "Garramartelo",
  "Machadofio",
  "Mão-de-Pedra",
  "Pé-de-Montanha",
  "Punhoférreo",
  "Rocha-Eterna",
  "Rúnico",
  "Safiraforja",
  "Serracume",
  "Sombraterra",
  "Talhapedra",
  "Três-Anéis",
  "Valedourado",
  "Ventoduro",
  "Vigia-de-Ferro",
  "Ysgardson",
];
const sobrenomes_anoes_baixa_classe = [
  "Barbacurto",
  "Caminhante",
  "Carvalho",
  "Cobreforja",
  "Ferreiro",
  "Forjador",
  "Lenhador",
  "Minerador",
  "Pedreiro",
  "Pó-de-Pedra",
  "Rocha",
  "Simples",
  "Terraplana",
  "Cava-Túneis",
  "Grosseiro",
  "Martelinho",
  "Pé-pesado",
  "Quebra-pedra",
  "Testadura",
  "Vigiamuro",
];
const nomes_masculinos_anoes = [
  "Borin",
  "Brok",
  "Darvin",
  "Dulin",
  "Durin",
  "Einar",
  "Flinn",
  "Garin",
  "Gimli",
  "Goran",
  "Haldor",
  "Harkin",
  "Kael",
  "Korgan",
  "Magnus",
  "Morgran",
  "Olaf",
  "Roric",
  "Thrain",
  "Ulric",
  "Balin",
  "Bardin",
  "Bran",
  "Dolgan",
  "Dwalin",
  "Fargrim",
  "Garth",
  "Grumbar",
  "Hreidmar",
  "Kildrak",
  "Morigan",
  "Nain",
  "Orik",
  "Rune",
  "Thorek",
  "Torvin",
  "Vorlag",
  "Wulfgar",
  "Yarvin",
  "Alberich",
  "Bjorn",
  "Dagrun",
  "Eldrin",
  "Fendrel",
  "Gareth",
  "Hrolf",
  "Kaelen",
  "Lodur",
  "Morkul",
];
const nomes_femininos_anoes = [
  "Astrid",
  "Borghild",
  "Brunhild",
  "Dagmar",
  "Daria",
  "Elda",
  "Frea",
  "Greta",
  "Griselda",
  "Helga",
  "Hildegard",
  "Ingrid",
  "Kira",
  "Lif",
  "Petra",
  "Ragna",
  "Saga",
  "Sigrid",
  "Thora",
  "Ursa",
  "Bardr",
  "Berta",
  "Dagny",
  "Eilif",
  "Frida",
  "Gerda",
  "Hella",
  "Idunn",
  "Kaysa",
  "Lena",
  "Nanna",
  "Olga",
  "Runa",
  "Solveig",
  "Thrud",
  "Vigdís",
  "Yrsa",
  "Aila",
  "Britta",
  "Dora",
  "Elin",
  "Fenja",
  "Gudrun",
  "Hanna",
  "Jorunn",
  "Karla",
  "Marta",
];
const sobrenomes_drow_alta_classe = [
  "Auvryndar",
  "Barrison Del'Armgo",
  "Despana",
  "Do'Urden",
  "Everhate",
  "Faen Tlabbar",
  "Freth",
  "Godeep",
  "Helviiryn",
  "Hune",
  "Kenafin",
  "Mizzrym",
  "Noquar",
  "Oblodra",
  "Ousstyl",
  "Srinshee",
  "T'sarran",
  "Vandree",
  "Xorlarrin",
  "Yaeldrin",
];
const sobrenomes_drow_baixa_classe = [
  "Blackblood",
  "Darkfang",
  "Duskcloak",
  "Gloomweb",
  "Nightshade",
  "Shadowbrook",
  "Silentstep",
  "Stonefall",
  "Undergloom",
  "Webspinner",
  "Deepdweller",
  "Graveborne",
  "Lostlight",
  "Rockfall",
  "Slyblade",
  "Spiderkiss",
  "Subterrane",
  "Twistedmind",
  "Venomhand",
  "Wormtongue",
];
const nomes_masculinos_drow = [
  "Aydan",
  "Belgos",
  "Berg'inyon",
  "Bhyrin",
  "Cael",
  "Drizzt",
  "Enkidu",
  "G'eld",
  "Guldor",
  "Horgar",
  "Ilmryn",
  "Jarlaxle",
  "Kael",
  "K'yorl",
  "Mavros",
  "Myrddin",
  "Naros",
  "Pharaun",
  "Quil",
  "Rizzen",
  "Ryld",
  "Sariel",
  "Szordrin",
  "Taziel",
  "Ulfgar",
  "Vorn",
  "Xal",
  "Xellos",
  "Yvon",
  "Zad",
  "Adran",
  "Byrnes",
  "Charon",
  "Dinin",
  "Erdan",
  "Faerl",
  "Glim",
  "Haram",
  "Istyr",
  "Jalyn",
  "Kier",
  "Lorax",
  "Malak",
  "Nym",
  "Olyran",
  "Phyrra",
  "Quentyn",
  "Rylon",
  "Solaufein",
  "Valas",
];
const nomes_femininos_drow = [
  "Aasira",
  "Alina",
  "Bela",
  "Briza",
  "Chalira",
  "Eilistraee",
  "Faeryl",
  "Glarath",
  "Haelina",
  "Ilyra",
  "Jezzara",
  "Ky'lar",
  "Liriel",
  "Malice",
  "Mournblade",
  "Phyrra",
  "Qilue",
  "Ryssa",
  "Shal",
  "Solomon",
  "Triel",
  "Ulfa",
  "Viconia",
  "Xandra",
  "Yashira",
  "Zelena",
  "Aerth",
  "Byrde",
  "Chey",
  "Dirina",
  "Elam",
  "Fae",
  "Gella",
  "Helena",
  "Ily",
  "Jyne",
  "Kiara",
  "Llora",
  "Menoly",
  "Nilona",
  "Orla",
  "Phara",
  "Quill",
  "Ryl",
  "Sena",
  "Syl",
  "Tiriel",
  "Umrae",
  "Velvet",
  "Xan",
  "Yath",
  "Zylna",
];
const sobrenomes_halfling_sem_classe = [
  "Bombolinho",
  "Bosquedourado",
  "Campogrande",
  "Colinaverde",
  "Corredeira",
  "Córrego-Claro",
  "Folhaclara",
  "Gorducho",
  "Mãos-Leves",
  "Pé-de-Pelo",
  "Pão-do-Dia",
  "Riacho Doce",
  "Sabugueiro",
  "Salgueiro-Fiel",
  "Sombra-Amiga",
  "Terraplena",
  "Touceira",
  "Valedoce",
  "Vila-Velha",
  "Xi-Xi",
];
const nomes_masculinos_halfling = [
  "Aldo",
  "Arlo",
  "Bilbo",
  "Borin",
  "Caleb",
  "Corbin",
  "Darian",
  "Digby",
  "Emmet",
  "Finnan",
  "Frodo",
  "Gavin",
  "Jasper",
  "Kael",
  "Liam",
  "Milo",
  "Nolan",
  "Oscar",
  "Pippin",
  "Quinn",
  "Reuben",
  "Roscoe",
  "Samwise",
  "Tobias",
  "Wilbur",
  "Alfie",
  "Barnaby",
  "Brandt",
  "Cian",
  "Darren",
  "Edgar",
  "Fabian",
  "Gilbert",
  "Harper",
  "Ivo",
  "Jethro",
  "Kieran",
  "Lionel",
  "Marnie",
  "Ned",
  "Oren",
  "Percy",
  "Ronan",
  "Silas",
  "Thorne",
  "Winston",
  "Xander",
  "Yancy",
  "Zephyr",
  "Cole",
];
const nomes_femininos_halfling = [
  "Anya",
  "Belladonna",
  "Briar",
  "Clover",
  "Daisy",
  "Elara",
  "Flora",
  "Gracie",
  "Hazel",
  "Holly",
  "Iris",
  "Jasmine",
  "Lavender",
  "Lily",
  "Marigold",
  "Myrtle",
  "Nessa",
  "Olive",
  "Poppy",
  "Primrose",
  "Rose",
  "Willow",
  "Willowby",
  "Xenia",
  "Yarrow",
  "Zinnia",
  "April",
  "Betony",
  "Briony",
  "Cheryl",
  "Daphne",
  "Eden",
  "Fawn",
  "Ginger",
  "Hallie",
  "Ivy",
  "June",
  "Kitty",
  "Lila",
  "Maple",
  "Nellie",
  "Orla",
  "Pansy",
  "Rowan",
  "Sage",
  "Tansy",
  "Violet",
  "Wendy",
  "Zara",
  "Joy",
  "Penny",
];
const nomes_masculinos_demonios = [
  "Azgath",
  "Borgul",
  "Cthon",
  "Dra'gul",
  "Erebus",
  "Falgor",
  "Grolak",
  "Hax",
  "Ignis",
  "Jorlak",
  "Kaelenor",
  "Lorthus",
  "Malakar",
  "N'gath",
  "Orlag",
  "Phyr",
  "Q'zoth",
  "Raxus",
  "Skar",
  "Thrax",
  "Urgok",
  "Vrak",
  "Xy'lar",
  "Ygrax",
  "Zar'ak",
  "Abhor",
  "Blekar",
  "Cinder",
  "Dreg",
  "Enk'mar",
  "Fellax",
  "Grimnyl",
  "Harkon",
  "Iz'rath",
  "Jurgol",
  "K'tharr",
  "Lykos",
  "Mortug",
  "Nyxus",
  "Olgark",
  "Prydon",
  "Quorl",
  "Rendak",
  "Stygian",
  "Thul",
  "Ulk'nar",
  "Vesk",
  "Xyth",
  "Yarog",
  "Zoltan",
];
const nomes_femininos_demonios = [
  "Aelith",
  "Blythe",
  "Crysa",
  "Draka",
  "Emberia",
  "Faelan",
  "Gloomia",
  "Hexus",
  "Illyria",
  "Jareth",
  "Kaelia",
  "Lyraxia",
  "Malvora",
  "Nyxara",
  "Orzara",
  "Phantasmia",
  "Quela",
  "Ryloth",
  "Sombra",
  "Theraxia",
  "Umbrae",
  "Vexia",
  "Xylara",
  "Yssal",
  "Zareth",
  "Acheron",
  "Briarwyn",
  "Corvina",
  "Direna",
  "Elithia",
  "Feronia",
  "Grimara",
  "Hellebore",
  "Iskara",
  "Jezara",
  "Kithra",
  "Lysandra",
  "Morwen",
  "Nethys",
  "Oblivia",
  "Pestila",
  "Quillara",
  "Raxina",
  "Stygia",
  "Tenebra",
  "Vespera",
  "Wyrmara",
  "Xanthia",
  "Yseria",
  "Zelma",
];
const titulos_demoniacos_menores = [
  "Cão de Carcaça",
  "Sussurrador das Trevas",
  "Olho da Tentação",
  "Ferrão das Sombras",
  "Gargula de Pedregulhos",
  "Lorde da Ferrugem",
  "Portador do Azar",
  "Rastreador Noturno",
  "Devorador de Ossos",
  "O Guardião da Dor",
  "Serpente da Podridão",
  "Mão Esquelética",
  "Verme da Dúvida",
  "Assecla da Corrupção",
  "Eco do Tormento",
  "Aura Fétida",
  "Escravo da Chama",
  "Queimador de Carne",
  "Dente Quebrado",
  "O Veloz do Submundo",
];
const titulos_demoniacos_maiores = [
  "O Flagelo de Almas",
  "O Devorador de Éons",
  "A Ruína dos Mundos",
  "Senhor da Peste Sussurrante",
  "O Conjurador de Cataclismos",
  "Príncipe da Carne Retorcida",
  "A Sombra Que Sangra",
  "O Corruptor Inominável",
  "Mestre das Chamas Eternas",
  "O Arauto do Caos",
  "O Tormento sem Fim",
  "Rei dos Abismos Estelares",
  "O Enganador Imortal",
  "Alma Gélida do Tártaro",
  "O Pesadelo Vivo",
  "Profanador dos Sagrados",
  "A Lâmina da Desesperança",
  "O Quebrador de Vontades",
  "A Voz do Vazio",
  "Titã da Destruição",
];
const sobrenomes_orcs = [
  "Garra Quebrada",
  "Crânio Rachado",
  "Dente Sangrento",
  "Pele Verde",
  "Martelo de Guerra",
  "Punho de Pedra",
  "Olho de Corvo",
  "Lâmina Cega",
  "Canto da Destruição",
  "Fúria Bruta",
];
const nomes_masculinos_orcs = [
  "Grak",
  "Throg",
  "Mog",
  "Bor",
  "Ruk",
  "Skorn",
  "Drogg",
  "Grom",
  "Korg",
  "Snarl",
  "Horg",
  "Grash",
  "Volk",
  "Ragnok",
  "Urza",
  "Frak",
  "Zurg",
  "Murd",
  "Krash",
  "Vorlag",
];
const nomes_femininos_orcs = [
  "Grima",
  "Tharka",
  "Morka",
  "Borgi",
  "Ruga",
  "Skarla",
  "Drogna",
  "Grama",
  "Karga",
  "Snarlia",
  "Horgra",
  "Grisha",
  "Volka",
  "Ragna",
  "Urzaa",
  "Franka",
  "Zurga",
  "Murda",
  "Krasha",
  "Vorla",
];
const sobrenomes_gnomos = [
  "Cobrechifre",
  "Engrenagem",
  "Faísca Alegre",
  "Favo de Mel",
  "Folhaverde",
  "Luzidia",
  "Pó de Estrela",
  "Riachoclaro",
  "Sussurrante",
  "Tecelão de Sonhos",
];
const nomes_masculinos_gnomos = [
  "Alston",
  "Bardin",
  "Brocc",
  "Caleb",
  "Derrick",
  "Elden",
  "Fimble",
  "Gimble",
  "Grickle",
  "Horace",
  "Jaster",
  "Kellen",
  "Levin",
  "Milo",
  "Nim",
  "Orrin",
  "Pippin",
  "Quinn",
  "Sven",
  "Wimble",
];
const nomes_femininos_gnomos = [
  "Anya",
  "Briar",
  "Celia",
  "Dina",
  "Elara",
  "Faelan",
  "Glimmer",
  "Holly",
  "Iris",
  "Jessa",
  "Kira",
  "Lira",
  "Mila",
  "Nessa",
  "Olga",
  "Pia",
  "Quilla",
  "Rina",
  "Sylvie",
  "Willow",
];
const sobrenomes_draconicos = [
  "Canto da Estrela Cadente",
  "Devorador de Montanhas",
  "Escama do Céu Tempestuoso",
  "Guardião do Tesouro Celestial",
  "Lâmina Gélida do Coração do Mundo",
  "Manto da Chama Eterna",
  "Portador da Ruína Antiga",
  "Sopro do Caos Resplandecente",
  "Tempestade de Cristal do Abismo",
  "Verme da Terra Profunda",
];
const nomes_masculinos_draconicos = [
  "Arjhanaxus",
  "Balasarion",
  "Bharashk'tharr",
  "Donaarion",
  "Ghessharkon",
  "Krivolax",
  "Mijir'okthos",
  "Nadarrion",
  "Patrinax",
  "Rhogarax",
  "Sovannox",
  "Torinnus",
  "Vaerthos",
  "Valenarion",
  "Vargash'thar",
  "Vorlag'roth",
  "Zarkosian",
  "Caldaronis",
  "Drakonthar",
  "Ignisthos",
];
const nomes_femininos_draconicos = [
  "Akraxia",
  "Biridora",
  "Daaralys",
  "Faridehla",
  "Harannael",
  "Jaxisarra",
  "Kaelenora",
  "Mehenestra",
  "Naomyssa",
  "Perralyn",
  "Raianna",
  "Soralia",
  "Thavael",
  "Urminara",
  "Vaerisia",
  "Verasath",
  "Xyliana",
  "Zinniaira",
  "Anyael",
  "Irinax",
];
const sobrenomes_goblins = [
  "Dedo Sujo",
  "Nariz Torto",
  "Olho Roxo",
  "Pé Manchado",
  "Pele Verde",
  "Quebra-Ossos",
  "Rabugento",
  "Rato do Esgoto",
  "Toca-Buraco",
  "Unha Quebrada",
];
const nomes_masculinos_goblins = [
  "Blargh",
  "Clank",
  "Dunk",
  "Fizban",
  "Grak",
  "Hork",
  "Jank",
  "Klarg",
  "Mok",
  "Narg",
  "Oog",
  "Pim",
  "Runt",
  "Skarg",
  "Snag",
  "Thunk",
  "Urg",
  "Vrak",
  "Wort",
  "Zarg",
];
const nomes_femininos_goblins = [
  "Borka",
  "Clinka",
  "Drizza",
  "Fizza",
  "Grima",
  "Horka",
  "Janka",
  "Klarissa",
  "Morka",
  "Narga",
  "Ooga",
  "Pimma",
  "Runta",
  "Skarga",
  "Snaga",
  "Thunka",
  "Urga",
  "Vraka",
  "Worta",
  "Zarga",
];

export const nomes_elficos: ConfiguracaoNomes = {
  nome: {
    masculino: nomes_masculinos_elficos,
    feminino: nomes_femininos_elficos,
  },
  sobrenome: {
    alta_classe: sobrenomes_elficos_alta_classe,
    baixa_classe: sobrenomes_elficos_baixa_classe,
  },
};

export const nomes_humanos_ocidentais: ConfiguracaoNomes = {
  nome: {
    masculino: nomes_masculinos_humanos_ocidental,
    feminino: nomes_femininos_humanos_ocidental,
  },
  sobrenome: {
    alta_classe: sobrenomes_humanos_alta_classe_ocidental,
    baixa_classe: sobrenomes_humanos_baixa_classe_ocidental,
  },
};

export const nomes_humanos_orientais: ConfiguracaoNomes = {
  nome: {
    masculino: nomes_masculinos_humanos_oriental,
    feminino: nomes_femininos_humanos_oriental,
  },
  sobrenome: {
    alta_classe: sobrenomes_humanos_alta_classe_oriental,
    baixa_classe: sobrenomes_humanos_baixa_classe_oriental,
  },
};

export const nomes_anoes: ConfiguracaoNomes = {
  nome: {
    masculino: nomes_masculinos_anoes,
    feminino: nomes_femininos_anoes,
  },
  sobrenome: {
    alta_classe: sobrenomes_anoes_alta_classe,
    baixa_classe: sobrenomes_anoes_baixa_classe,
  },
};

export const nomes_drow: ConfiguracaoNomes = {
  nome: {
    masculino: nomes_masculinos_drow,
    feminino: nomes_femininos_drow,
  },
  sobrenome: {
    alta_classe: sobrenomes_drow_alta_classe,
    baixa_classe: sobrenomes_drow_baixa_classe,
  },
};

export const nomes_halfling: ConfiguracaoNomes = {
  nome: {
    masculino: nomes_masculinos_halfling,
    feminino: nomes_femininos_halfling,
  },
  sobrenome: {
    sem_classe: sobrenomes_halfling_sem_classe,
  },
};

export const nomes_demonios: ConfiguracaoNomes = {
  nome: {
    masculino: nomes_masculinos_demonios,
    feminino: nomes_femininos_demonios,
  },
  sobrenome: {
    sem_classe: titulos_demoniacos_menores,
  },
};

export const nomes_orcs: ConfiguracaoNomes = {
  nome: {
    masculino: nomes_masculinos_orcs,
    feminino: nomes_femininos_orcs,
  },
  sobrenome: {
    sem_classe: sobrenomes_orcs,
  },
};

export const nomes_gnomos: ConfiguracaoNomes = {
  nome: {
    masculino: nomes_masculinos_gnomos,
    feminino: nomes_femininos_gnomos,
  },
  sobrenome: {
    sem_classe: sobrenomes_gnomos,
  },
};

export const nomes_draconicos: ConfiguracaoNomes = {
  nome: {
    masculino: nomes_masculinos_draconicos,
    feminino: nomes_femininos_draconicos,
  },
  sobrenome: {
    sem_classe: sobrenomes_draconicos,
  },
};

export const nomes_goblins: ConfiguracaoNomes = {
  nome: {
    masculino: nomes_masculinos_goblins,
    feminino: nomes_femininos_goblins,
  },
  sobrenome: {
    sem_classe: sobrenomes_goblins,
  },
};
